version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./app/src/data:/app/app/src/data
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
    restart: unless-stopped

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
      - /app/node_modules # prevent local node_modules from being overwritten
      - ./app/src/data:/app/src/data
    environment:
      - CHOKIDAR_USEPOLLING=true # ensure hmr works across some file systems
      - VITE_API_URL=http://localhost:8000
    restart: unless-stopped
    depends_on:
      - api
